apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: transaction-api-read-config
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["transaction-api-config"]
    verbs: ["get"]
