{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transaction-api
  namespace: {{ .Values.namespace }}
  labels:
{{ toYaml .Values.serviceMonitor.labels | indent 4 }}
spec:
  selector:
    matchLabels:
      app: transaction-api
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
