grafana:
  adminPassword: "ChangeMe-Strong-Password!"
  service:
    type: LoadBalancer
  defaultDashboardsEnabled: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: secure-transaction-api
          orgId: 1
          folder: Secure Transaction API
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/secure-transaction-api
  dashboardsConfigMaps:
    secure-transaction-api: secure-transaction-api-dashboard

prometheus:
  prometheusSpec:
    retention: 7d
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
