apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transaction-api
  namespace: secure-bank
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: transaction-api
  namespaceSelector:
    matchNames:
      - secure-bank
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
